-- ============================================================
--  MODULE DE FACTURATION - SPRINVOICES
--  Script de création des tables Oracle
--  Ordre : ROLE > USER_ACCOUNT > CUSTOMER > PRODUCT > INVOICE > INVOICE_ROW
-- ============================================================

-- Suppression dans l'ordre inverse (évite les erreurs de FK)
DROP TABLE INVOICE_ROW   CASCADE CONSTRAINTS PURGE;
DROP TABLE INVOICE       CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUCT       CASCADE CONSTRAINTS PURGE;
DROP TABLE CUSTOMER      CASCADE CONSTRAINTS PURGE;
DROP TABLE USER_ACCOUNT  CASCADE CONSTRAINTS PURGE;
DROP TABLE ROLE          CASCADE CONSTRAINTS PURGE;

-- ============================================================
-- 1. TABLE ROLE
--    Contient les deux rôles : ADMIN et CLIENT
-- ============================================================
CREATE TABLE ROLE (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

-- ============================================================
-- 2. TABLE USER_ACCOUNT
--    Les utilisateurs de l'application.
--    On évite le mot réservé "USER" d'Oracle → USER_ACCOUNT
--    Chaque utilisateur a un rôle (FK vers ROLE)
-- ============================================================
CREATE TABLE USER_ACCOUNT (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,  -- identifiant de connexion
    password VARCHAR2(255) NOT NULL,          -- mot de passe hashé (BCrypt)
    enabled  NUMBER(1)     DEFAULT 1 NOT NULL, -- 1 = actif, 0 = désactivé
    role_id  NUMBER        NOT NULL,
    CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES ROLE(id)
);

-- ============================================================
-- 3. TABLE CUSTOMER
--    Les clients de SprinVoices.
--    Chaque client possède un compte utilisateur (FK vers USER_ACCOUNT)
--    Le champ "delay" représente le délai de paiement en jours.
-- ============================================================
CREATE TABLE CUSTOMER (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR2(100) NOT NULL,
    corporate_name VARCHAR2(150),              -- raison sociale
    address        VARCHAR2(255),
    zipcode        VARCHAR2(10),
    city           VARCHAR2(100),
    delay          NUMBER DEFAULT 30 NOT NULL, -- délai de paiement (jours)
    user_id        NUMBER UNIQUE,              -- UNIQUE : 1 client = 1 compte
    CONSTRAINT fk_customer_user FOREIGN KEY (user_id) REFERENCES USER_ACCOUNT(id)
);

-- ============================================================
-- 4. TABLE PRODUCT
--    Le catalogue de produits/prestations facturables.
-- ============================================================
CREATE TABLE PRODUCT (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(200) NOT NULL,
    unit_price  NUMBER(10, 2) NOT NULL,  -- prix unitaire HT
    description VARCHAR2(500),
    category    VARCHAR2(100)
);

-- ============================================================
-- 5. TABLE INVOICE
--    Les factures. Une facture appartient à un client.
--    États possibles :
--      - CREATED   : created_at renseigné, invoiced_at NULL, paid_at NULL
--      - INVOICED  : invoiced_at renseigné, paid_at NULL
--      - PAID      : paid_at renseigné
-- ============================================================
CREATE TABLE INVOICE (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(200) NOT NULL,       -- libellé de la facture
    created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    invoiced_at TIMESTAMP,                    -- NULL tant que non facturée
    paid_at     TIMESTAMP,                    -- NULL tant que non payée
    customer_id NUMBER        NOT NULL,
    CONSTRAINT fk_invoice_customer FOREIGN KEY (customer_id) REFERENCES CUSTOMER(id),
    -- Cohérence des dates : invoiced_at >= created_at, paid_at >= invoiced_at
    CONSTRAINT chk_invoice_dates CHECK (
        (invoiced_at IS NULL OR invoiced_at >= created_at)
        AND
        (paid_at IS NULL OR (invoiced_at IS NOT NULL AND paid_at >= invoiced_at))
    )
);

-- ============================================================
-- 6. TABLE INVOICE_ROW
--    Les lignes d'une facture : 1 ligne = 1 produit + quantité
--    Le montant est calculé : unit_price * quantity (méthode amount())
-- ============================================================
CREATE TABLE INVOICE_ROW (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity   NUMBER(10, 3) NOT NULL,          -- quantité (ex: 2.5 heures)
    invoice_id NUMBER        NOT NULL,
    product_id NUMBER        NOT NULL,
    CONSTRAINT fk_row_invoice FOREIGN KEY (invoice_id) REFERENCES INVOICE(id) ON DELETE CASCADE,
    CONSTRAINT fk_row_product FOREIGN KEY (product_id) REFERENCES PRODUCT(id),
    CONSTRAINT chk_quantity_positive CHECK (quantity > 0)
);

-- ============================================================
-- DONNÉES INITIALES
-- ============================================================

-- Rôles
INSERT INTO ROLE (name) VALUES ('ROLE_ADMIN');
INSERT INTO ROLE (name) VALUES ('ROLE_CLIENT');

-- Utilisateur admin par défaut (mot de passe : "admin123" hashé en BCrypt)
-- Hash généré pour : admin123
INSERT INTO USER_ACCOUNT (username, password, enabled, role_id)
VALUES ('admin', '$2a$12$g.AZcUxKcLJOwFTt8gKTHO9rHCG4mRFyRSjZCo1.WUVYRE5M3zDyu', 1,
        (SELECT id FROM ROLE WHERE name = 'ROLE_ADMIN'));

-- Quelques produits de démonstration
INSERT INTO PRODUCT (designation, unit_price, description, category)
VALUES ('Prestation de conseil', 150.00, 'Conseil stratégique et accompagnement', 'Conseil');

INSERT INTO PRODUCT (designation, unit_price, description, category)
VALUES ('Développement web', 75.00, 'Développement d''application web sur mesure', 'Développement');

INSERT INTO PRODUCT (designation, unit_price, description, category)
VALUES ('Formation', 500.00, 'Session de formation (journée complète)', 'Formation');

INSERT INTO PRODUCT (designation, unit_price, description, category)
VALUES ('Audit technique', 200.00, 'Audit et rapport de recommandations', 'Conseil');

COMMIT;

-- ============================================================
-- VÉRIFICATION
-- ============================================================

ALTER TABLE INVOICE ADD fac_number VARCHAR2(20) UNIQUE;


SELECT table_name FROM user_tables
WHERE table_name IN ('ROLE','USER_ACCOUNT','CUSTOMER','PRODUCT','INVOICE','INVOICE_ROW')
ORDER BY table_name;


CREATE TABLE QUOTE (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_number      VARCHAR2(20) UNIQUE,
    designation VARCHAR2(200) NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    sent_at     TIMESTAMP,
    status      VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    customer_id NUMBER NOT NULL,
    CONSTRAINT fk_quote_customer FOREIGN KEY (customer_id) REFERENCES CUSTOMER(id),
    CONSTRAINT chk_quote_status CHECK (status IN ('DRAFT','SENT','ACCEPTED','REFUSED'))
);

CREATE TABLE QUOTE_ROW (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity   NUMBER(10,3) NOT NULL,
    quote_id   NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    CONSTRAINT fk_quoterow_quote   FOREIGN KEY (quote_id)   REFERENCES QUOTE(id) ON DELETE CASCADE,
    CONSTRAINT fk_quoterow_product FOREIGN KEY (product_id) REFERENCES PRODUCT(id),
    CONSTRAINT chk_quote_qty CHECK (quantity > 0)
);


CREATE TABLE password_reset_token (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token           VARCHAR2(255) NOT NULL,
    user_account_id NUMBER        NOT NULL,
    expires_at      TIMESTAMP     NOT NULL,

    CONSTRAINT fk_prt_user
        FOREIGN KEY (user_account_id)
        REFERENCES user_account(id)
        ON DELETE CASCADE
);